from pydantic import BaseModel, Field

class IngestRequest(BaseModel):
    """Schema representing document ingestion input payload."""
    content: str = Field(..., min_length=10, description="The raw text document content to index.")
    metadata: dict = Field(default_factory=dict, description="Arbitrary key-value metadata pairs.")

class QueryRequest(BaseModel):
    """Schema representing user natural language search input query."""
    question: str = Field(..., min_length=3, description="The question targeting the context database.")

class QueryResponse(BaseModel):
    """Schema mapping successful RAG pipeline responses."""
    answer: str = Field(..., description="The context-grounded response generated by Llama3.")
    source_documents: list[str] = Field(..., description="The text chunks extracted and used as context.")
